stages:
  - validate
  - test
  - package
  - site
  - pages

image: maven:3.9-eclipse-temurin-21

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key:
    files:
      - pom.xml
  paths:
    - .m2/repository
  policy: pull-push

validate:
  stage: validate
  script:
    - mvn $MAVEN_CLI_OPTS validate
  rules:
    - changes:
        - '**/*'

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    paths:
      - target/surefire-reports/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  rules:
    - changes:
        - '**/*'

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
    - ls -lh target/
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  rules:
    - changes:
        - '**/*'

site:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS site
  artifacts:
    paths:
      - target/site/
    expire_in: 1 week
  rules:
    - changes:
        - '**/*'

pages:
  stage: pages
  dependencies:
    - site
  script:
    - mkdir -p public
    - cp -r target/site/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  rules:
    - changes:
        - '**/*'