image: maven:3.9-eclipse-temurin-21

stages:
  - validate
  - test
  - package
  - site
  - deploy
  - pages

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key:
    files:
      - pom.xml
  paths:
    - .m2/repository
  policy: pull-push

validate:
  stage: validate
  script:
    - mvn $MAVEN_CLI_OPTS validate

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests
    - ls -lh target/
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

site:
  stage: site
  script:
    - mvn $MAVEN_CLI_OPTS site
  artifacts:
    paths:
      - target/site
    expire_in: 1 week
  only:
    - main

pages:
  stage: pages
  dependencies:
    - site
  script:
    - mkdir -p public
    - cp -r target/site/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - package
  script:
    - echo "Looking for JAR file..."
    - JAR_PATH=$(find target -name 'fridgely-*.jar' | head -n1)
    - if [ -z "$JAR_PATH" ]; then echo "❌ JAR file not found!"; exit 1; fi
    - cp "$JAR_PATH" fridgely-latest.jar
    - echo "✅ JAR copied to fridgely-latest.jar"
    - |
      release-cli create \
        --description "Release from Pipeline $CI_PIPELINE_IID - All tests and checks passed" \
        --tag-name "v$CI_PIPELINE_IID" \
        --assets-link "{\"name\":\"Fridgely JAR\",\"url\":\"$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/fridgely-latest.jar\"}"
  artifacts:
    paths:
      - fridgely-latest.jar
    expire_in: 1 month
  only:
    - main
  when: on_success
